<?php

/**

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

$ar = [];
f(1,2);
function f($a,$b){
  global $ar;
  if($b<4000000){
    if($b%2==0) $ar[] = $b;
    f($b, $a+$b);
  }
}

echo array_sum($ar);